version: '2'
services:

    sender:
        build: Workers/Sender
        command: python send.py 
        tty: true

    rabbitmq:
        image: rabbitmq:3.6-management

    receiver0:
        build: 
            context: Receiver 

        entrypoint: "python3 receive.py"

    receiver1:
        build: 
            context: Receiver 
                
        entrypoint: "python3 receive.py"

    receiver2:
        build: 
            context: Receiver 

        entrypoint: "python3 receive.py"

